// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB7M7h-Ok105TSkwXpyoPcTnxSbScwxSN4',
    appId: '1:39055464779:web:c3a9bd5a475609578af0ce',
    messagingSenderId: '39055464779',
    projectId: 'fbla-mobile-app-2024',
    authDomain: 'fbla-mobile-app-2024.firebaseapp.com',
    storageBucket: 'fbla-mobile-app-2024.appspot.com',
    measurementId: 'G-M9EBYYJ936',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDY384L9FVLNmJ0l_C_boqGywbocGwES6M',
    appId: '1:39055464779:android:cbb2fc72b6483af68af0ce',
    messagingSenderId: '39055464779',
    projectId: 'fbla-mobile-app-2024',
    storageBucket: 'fbla-mobile-app-2024.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBvv_5BaPx9WVBmQfjpT8qD8Tc7vLj413k',
    appId: '1:39055464779:ios:7e3a3ac515d2ecf78af0ce',
    messagingSenderId: '39055464779',
    projectId: 'fbla-mobile-app-2024',
    storageBucket: 'fbla-mobile-app-2024.appspot.com',
    iosClientId: '39055464779-gk87lcfh1ma3dgjrtpfsd2q6q61q16jj.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbla2024',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBvv_5BaPx9WVBmQfjpT8qD8Tc7vLj413k',
    appId: '1:39055464779:ios:f80117e2f020919b8af0ce',
    messagingSenderId: '39055464779',
    projectId: 'fbla-mobile-app-2024',
    storageBucket: 'fbla-mobile-app-2024.appspot.com',
    iosClientId: '39055464779-5d96umsedf80rtot5chd6pti97jf2hmo.apps.googleusercontent.com',
    iosBundleId: 'com.example.fbla2024.RunnerTests',
  );
}
